networks:
  public-network:
    driver: bridge
services:
  db:
    image: postgres:15
    container_name: codechat_postgres
    restart: unless-stopped
    networks:
      - public-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: codechat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    container_name: codechat_api
    image: codechat/api:v1.3.0
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - public-network
    ports:
      - "8084:8084"
    env_file:
      - .env
    volumes:
      - instances_connecteds:/codechat/instances
    command: sh -c "
      echo '📦 Executando migrações Prisma...' &&
      npx prisma migrate deploy &&
      echo '🚀 Iniciando API...' &&
      node ./dist/src/main.js"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_PORT: ${SERVER_PORT}
      SESSION_SECRET: ${SESSION_HTTP_SECRET}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_COLOR: ${LOG_COLOR}
      AUTHENTICATION_GLOBAL_AUTH_TOKEN: ${AUTHENTICATION_GLOBAL_AUTH_TOKEN}
      NODE_OPTIONS: "--max-old-space-size=1024"
      DATABASE_ENABLED: "true"
      DATABASE_SYNC_MESSAGES: "true"
      DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
      DATABASE_SAVE_MESSAGE_UPDATE: "true"
      DATABASE_SAVE_DATA_CONTACTS: "true"
      DATABASE_SAVE_DATA_CHATS: "true"
      INSTANCE_EXPIRATION_TIME: "false"
      CONFIG_SESSION_PHONE_CLIENT: Chrome Linux
      CONFIG_SESSION_PHONE_NAME: Chrome
      WA_VERSION: "[2,3000,1024242101]"
      QRCODE_LIMIT: 30
      QRCODE_EXPIRATION_TIME: 180
      CONNECTION_TIMEOUT: 600
  ngrok:
    image: ngrok/ngrok:latest
    container_name: codechat_ngrok
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - public-network
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["ngrok", "http", "codechat_api:8084"]
    ports:
      - "4040:4040"

volumes:
  postgres_data:
  instances_connecteds:
